export { default as Head } from "./head"
export { default as Layout } from "./layout"
export { default as About } from "./sections/about"
export { default as Experience } from "./sections/experience/experience"
export { default as Contact } from "./sections/contact"
export { default as News } from "./sections/news"
export { default as Cv } from "./sections/cv"
export { default as Footer } from "./sections/footer"
